### ISSUE TITLE
analyse.js vs sonar-project.properties

### ISSUE THREAD

**Issue by ThYpHo0n** [SonarSource/SonarTS-example#3]
Hi,

first of all, thank you for the example projects. They are a great starting point.

I just can't get my head around using a dedicated analyze.js file instead of the good old sonar-project.properties - is there any particular reason why I shouldn't using it?

Additionally there's the following sentence in the readme of the Example 1 project:
> We recommend to set version of project manually through script file to not depend on the one from package.json

Why is depending on the package.json a bad thing? I don't want to maintain 2 different version strings in my projects which will most likely drift apart at some time because someone is lazy/forgot about the other one. And how does this solve the leaking problem? We solve that by running Sonar in preview mode for our feature branches and execute it with increased version on our release build.

**Comment by vilchik-elena** [comment]
Hi,

Sorry for the delay

First, why not using sonar-project.properties

If you are using [sonarqube-scanner for JavaScript](https://github.com/bellingard/sonar-scanner-npm), scanner will use `package.json` by default. And `sonar-project.properties` only if `package.json` is not found. So when `package.json` is there (probably your case) and you want to use [sonarqube-scanner for JavaScript](https://github.com/bellingard/sonar-scanner-npm) (it will enable export of project name, description, version from `package.json`)  then 1) write script (like the one in example) or 2) using command line

You always can use "good old" sonar-project.properties and standard scanner. But then you need to duplicate project name, version and description in package.json and sonar-project.properties


Second, why not using standard version from package.json

I agree, it's confusing. The problem is that the versioning of npm and of the one which SQ expects are different:
- for NPM e.g. during development of version 1.3 you package.json file will contain 1.2. You will update version only when doing release
- for SQ you should provide version which is under development now

It's not a big deal, but if you use default npm version in SQ your leak period will be "shifted" (or even incorrect if you use prereleases)

**Comment by ThYpHo0n** [comment]
Hi, thank you for the clarification 👍

In the Java/Maven world we version a bit different than NPM expects it I guess.
You wrote:
> for NPM e.g. during development of version 1.3 you package.json file will contain 1.2. You will update version only when doing release

I'm not a NPM expert but in Maven we would use something like 1.3-SNAPSHOT for snapshots/dev builds. For NPM I guess a pre-release tag like 1.3-ALPHA.$buildid would be similar.
But thats quite specific to the fundamental question how to version your project.

I would still like to get rid of handling two version strings in my project, I will play around a bit more with NPM versioning and check impacts on the SQ leak period.
